package settings

import (
	"encoding/json"
	"strings"
	"testing"

	"gotest.tools/v3/assert"
)

func TestMergeMinimalExisting(t *testing.T) {
	existing := []byte(`{}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]},
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "test", "timeout": 60}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))
	assert.Equal(t, merged["$schema"], "https://json.schemastore.org/claude-code-settings.json")
	assert.Equal(t, merged["_comment"], "Generated by chunk init.")
}

func TestMergePreservesUnknownKeys(t *testing.T) {
	existing := []byte(`{
		"env": {"FOO": "bar"},
		"model": "claude-sonnet",
		"permissions": {"allow": ["Read"]}
	}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	// Unknown keys preserved.
	env := merged["env"].(map[string]interface{})
	assert.Equal(t, env["FOO"], "bar")
	assert.Equal(t, merged["model"], "claude-sonnet")
}

func TestMergePermissionsAllowUnion(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Read", "Write"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)", "Read"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	allow := toStringSlice(perms["allow"])

	// All three values present, sorted, no duplicates.
	assert.DeepEqual(t, allow, []string{"Bash(chunk:*)", "Read", "Write"})
}

func TestMergePermissionsAllowNoDuplicate(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Bash(chunk:*)", "Read"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	allow := toStringSlice(perms["allow"])
	assert.DeepEqual(t, allow, []string{"Bash(chunk:*)", "Read"})
}

func TestMergePreservesOtherPermissionKeys(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Read"], "deny": ["Bash(rm *)"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	deny := toStringSlice(perms["deny"])
	assert.DeepEqual(t, deny, []string{"Bash(rm *)"})
}

func TestMergeHooksReplaceSameMatcher(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "old-cmd", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "new-cmd", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	hookEntries := group["hooks"].([]interface{})
	entry := hookEntries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "new-cmd")
}

func TestMergeHooksMigratesLegacyMatcher(t *testing.T) {
	// Existing settings written by an older chunk init (matcher on group, no if on entries).
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "old-cmd", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "new-cmd", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	// Legacy group replaced by new group — no duplicate.
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	assert.Equal(t, group["matcher"], "Bash")
	hookEntries := group["hooks"].([]interface{})
	entry := hookEntries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "new-cmd")
	assert.Equal(t, entry["if"], "Bash(git commit*)")
}

func TestMergeHooksPreservesDifferentMatcher(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Edit", "hooks": [{"type": "command", "command": "lint-check", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "commit-check", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 2)

	// Original group preserved.
	group0 := preToolUse[0].(map[string]interface{})
	assert.Equal(t, group0["matcher"], "Edit")

	// New group appended.
	group1 := preToolUse[1].(map[string]interface{})
	assert.Equal(t, group1["matcher"], "Bash")
}

func TestMergePreservesOtherHookTypes(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PostToolUse": [
				{"matcher": "*", "hooks": [{"type": "command", "command": "post-hook", "timeout": 10}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "pre-hook", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})

	// PostToolUse preserved.
	postToolUse := hooks["PostToolUse"].([]interface{})
	assert.Equal(t, len(postToolUse), 1)

	// PreToolUse added.
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)
}

// A repo that already had a settings.json before chunk init ran gets the Stop
// hook added, not just PreToolUse. Without it the repo keeps its commit hooks
// but never validates at session end.
func TestMergeAddsStopHookToExistingSettings(t *testing.T) {
	existing := []byte(`{
		"permissions": {"allow": ["Bash(task *)"]},
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "task test", "timeout": 300}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "cd . && task test", "timeout": 300}]}
			],
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 330}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop, ok := hooks["Stop"].([]interface{})
	assert.Assert(t, ok && len(stop) == 1, "expected a Stop hook group, got: %v", hooks["Stop"])

	group := stop[0].(map[string]interface{})
	entry := group["hooks"].([]interface{})[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "chunk validate")
	assert.Equal(t, entry["timeout"], float64(330))
}

// The chunk-managed Stop group is replaced in place so a changed timeout takes
// effect instead of stacking a second "chunk validate" entry.
func TestMergeReplacesStopHook(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 30}]}]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop := hooks["Stop"].([]interface{})
	assert.Equal(t, len(stop), 1)

	group := stop[0].(map[string]interface{})
	entry := group["hooks"].([]interface{})[0].(map[string]interface{})
	assert.Equal(t, entry["timeout"], float64(600))
}

// A Stop hook the user wrote themselves is left alone; chunk only manages its own.
func TestMergePreservesUserStopHooks(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [
				{"hooks": [{"type": "command", "command": "notify-send done", "timeout": 5}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop, ok := hooks["Stop"].([]interface{})
	assert.Assert(t, ok && len(stop) == 2, "expected both Stop groups to be present, got: %v", len(stop))
}

// A user entry sharing the group with chunk's own survives the merge. Chunk owns
// the "chunk validate" entry, not the group it happens to sit in, so the entry is
// replaced in place rather than the whole group being overwritten.
func TestMergePreservesUserEntriesInChunkStopGroup(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [
				{"hooks": [
					{"type": "command", "command": "chunk validate", "timeout": 30},
					{"type": "command", "command": "notify-send done", "timeout": 5}
				]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop := hooks["Stop"].([]interface{})
	assert.Equal(t, len(stop), 1)

	entries := stop[0].(map[string]interface{})["hooks"].([]interface{})
	assert.Equal(t, len(entries), 2)

	commands := make([]string, 0, len(entries))
	for _, e := range entries {
		entry := e.(map[string]interface{})
		cmd, _ := entry["command"].(string)
		commands = append(commands, cmd)
		if cmd == StopCommand {
			assert.Equal(t, entry["timeout"], float64(600))
		}
	}
	assert.DeepEqual(t, commands, []string{StopCommand, "notify-send done"})
}

func TestMergeNoChangeWhenAlreadyMerged(t *testing.T) {
	settings := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]},
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "test", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(settings, settings)
	assert.NilError(t, err)
	assert.Assert(t, !result.Changed)
}

func TestMergeGeneratedWithNoHooks(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "existing-cmd", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"permissions": {"allow": ["Bash(chunk:*)"]}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	// Existing hooks preserved when generated has no hooks.
	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	hookEntries := group["hooks"].([]interface{})
	entry := hookEntries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "existing-cmd")
}

func TestDiffShowsChanges(t *testing.T) {
	original := []byte(`{
  "permissions": {
    "allow": ["Read"]
  }
}`)
	merged := []byte(`{
  "permissions": {
    "allow": ["Bash(chunk:*)", "Read"]
  }
}`)

	diff := Diff(original, merged)
	assert.Assert(t, diff != "", "expected non-empty diff")
	assert.Assert(t, strings.Contains(diff, "---"))
	assert.Assert(t, strings.Contains(diff, "+++"))
	assert.Assert(t, strings.Contains(diff, "Bash(chunk:*)"))
}

func TestDiffEmptyWhenIdentical(t *testing.T) {
	data := []byte(`{"foo": "bar"}`)
	diff := Diff(data, data)
	assert.Equal(t, diff, "")
}

func TestMergeMalformedExisting(t *testing.T) {
	_, err := Merge([]byte(`not json`), []byte(`{}`))
	assert.ErrorContains(t, err, "parse existing settings")
}

func TestMergeMalformedGenerated(t *testing.T) {
	_, err := Merge([]byte(`{}`), []byte(`not json`))
	assert.ErrorContains(t, err, "parse generated settings")
}

func TestMergeCodexMinimalExisting(t *testing.T) {
	existing := []byte(`{}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "go test ./...", "timeout": 60}]}],
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 90}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	assert.Assert(t, hooks["PreToolUse"] != nil)
	assert.Assert(t, hooks["Stop"] != nil)
}

func TestMergeCodexPreservesOtherHookTypes(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PostToolUse": [{"matcher": "*", "hooks": [{"type": "command", "command": "audit", "timeout": 10}]}]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "test", "timeout": 60}]}],
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 90}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	assert.Assert(t, hooks["PostToolUse"] != nil, "PostToolUse must be preserved")
	assert.Assert(t, hooks["PreToolUse"] != nil)
	assert.Assert(t, hooks["Stop"] != nil)
}

func TestMergeCodexReplacesPreToolUseByMatcher(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "old-cmd", "timeout": 30}]}]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "new-cmd", "timeout": 60}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	entries := group["hooks"].([]interface{})
	entry := entries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "new-cmd")
}

func TestMergeCodexReplacesStopHook(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 30}]}]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop := hooks["Stop"].([]interface{})
	group := stop[0].(map[string]interface{})
	entries := group["hooks"].([]interface{})
	entry := entries[0].(map[string]interface{})
	timeout, _ := entry["timeout"].(float64)
	assert.Assert(t, timeout == 600, "expected updated stop timeout of 600, got: %v", timeout)
}

func TestMergeCodexPreservesUserStopHooks(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [
				{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 30}]},
				{"hooks": [{"type": "command", "command": "notify-team", "timeout": 10}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop, ok := hooks["Stop"].([]interface{})
	assert.Assert(t, ok && len(stop) == 2, "expected both Stop groups to be present, got: %v", len(stop))

	// Find the chunk-managed group and verify it was updated.
	for _, g := range stop {
		group, ok := g.(map[string]interface{})
		assert.Assert(t, ok, "expected stop group to be a map")
		entries, ok := group["hooks"].([]interface{})
		assert.Assert(t, ok && len(entries) > 0, "expected stop hook entries")
		entry, ok := entries[0].(map[string]interface{})
		assert.Assert(t, ok, "expected stop hook entry to be a map")
		if entry["command"] == "chunk validate" {
			timeout, _ := entry["timeout"].(float64)
			assert.Assert(t, timeout == 600, "expected updated chunk validate timeout, got: %v", timeout)
		}
	}
}

// The Codex path shares mergeStopHooks, so it keeps user entries that sit in the
// same group as chunk's own entry too.
func TestMergeCodexPreservesUserEntriesInChunkStopGroup(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"Stop": [
				{"hooks": [
					{"type": "command", "command": "notify-team", "timeout": 10},
					{"type": "command", "command": "chunk validate", "timeout": 30}
				]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 600}]}]
		}
	}`)

	result, err := MergeCodex(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	stop := hooks["Stop"].([]interface{})
	assert.Equal(t, len(stop), 1)

	entries := stop[0].(map[string]interface{})["hooks"].([]interface{})
	assert.Equal(t, len(entries), 2)

	// The user's entry keeps its position and timeout; chunk's is updated in place.
	first := entries[0].(map[string]interface{})
	assert.Equal(t, first["command"], "notify-team")
	assert.Equal(t, first["timeout"], float64(10))

	second := entries[1].(map[string]interface{})
	assert.Equal(t, second["command"], StopCommand)
	assert.Equal(t, second["timeout"], float64(600))
}

func TestMergeCodexNoChangeWhenAlreadyMerged(t *testing.T) {
	data := []byte(`{
		"hooks": {
			"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "if": "Bash(git commit*)", "command": "go test ./...", "timeout": 60}]}],
			"Stop": [{"hooks": [{"type": "command", "command": "chunk validate", "timeout": 90}]}]
		}
	}`)

	result, err := MergeCodex(data, data)
	assert.NilError(t, err)
	assert.Assert(t, !result.Changed)
}

func TestMergeCodexMalformedExisting(t *testing.T) {
	_, err := MergeCodex([]byte(`not json`), []byte(`{}`))
	assert.ErrorContains(t, err, "parse existing hooks")
}

func TestMergeCodexMalformedGenerated(t *testing.T) {
	_, err := MergeCodex([]byte(`{}`), []byte(`not json`))
	assert.ErrorContains(t, err, "parse generated hooks")
}
