package settings

import (
	"encoding/json"
	"strings"
	"testing"

	"gotest.tools/v3/assert"
)

func TestMergeMinimalExisting(t *testing.T) {
	existing := []byte(`{}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]},
		"hooks": {
			"PreToolUse": [{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "test", "timeout": 60}]}]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))
	assert.Equal(t, merged["$schema"], "https://json.schemastore.org/claude-code-settings.json")
	assert.Equal(t, merged["_comment"], "Generated by chunk init.")
}

func TestMergePreservesUnknownKeys(t *testing.T) {
	existing := []byte(`{
		"env": {"FOO": "bar"},
		"model": "claude-sonnet",
		"permissions": {"allow": ["Read"]}
	}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	// Unknown keys preserved.
	env := merged["env"].(map[string]interface{})
	assert.Equal(t, env["FOO"], "bar")
	assert.Equal(t, merged["model"], "claude-sonnet")
}

func TestMergePermissionsAllowUnion(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Read", "Write"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)", "Read"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	allow := toStringSlice(perms["allow"])

	// All three values present, sorted, no duplicates.
	assert.DeepEqual(t, allow, []string{"Bash(chunk:*)", "Read", "Write"})
}

func TestMergePermissionsAllowNoDuplicate(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Bash(chunk:*)", "Read"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	allow := toStringSlice(perms["allow"])
	assert.DeepEqual(t, allow, []string{"Bash(chunk:*)", "Read"})
}

func TestMergePreservesOtherPermissionKeys(t *testing.T) {
	existing := []byte(`{"permissions": {"allow": ["Read"], "deny": ["Bash(rm *)"]}}`)
	generated := []byte(`{"permissions": {"allow": ["Bash(chunk:*)"]}}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	perms := merged["permissions"].(map[string]interface{})
	deny := toStringSlice(perms["deny"])
	assert.DeepEqual(t, deny, []string{"Bash(rm *)"})
}

func TestMergeHooksReplaceSameMatcher(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "old-cmd", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "new-cmd", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)
	assert.Assert(t, result.Changed)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	hookEntries := group["hooks"].([]interface{})
	entry := hookEntries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "new-cmd")
}

func TestMergeHooksPreservesDifferentMatcher(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git push*)", "hooks": [{"type": "command", "command": "push-check", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "commit-check", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 2)

	// Original group preserved.
	group0 := preToolUse[0].(map[string]interface{})
	assert.Equal(t, group0["matcher"], "Bash(git push*)")

	// New group appended.
	group1 := preToolUse[1].(map[string]interface{})
	assert.Equal(t, group1["matcher"], "Bash(git commit*)")
}

func TestMergePreservesOtherHookTypes(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PostToolUse": [
				{"matcher": "*", "hooks": [{"type": "command", "command": "post-hook", "timeout": 10}]}
			]
		}
	}`)
	generated := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "pre-hook", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	hooks := merged["hooks"].(map[string]interface{})

	// PostToolUse preserved.
	postToolUse := hooks["PostToolUse"].([]interface{})
	assert.Equal(t, len(postToolUse), 1)

	// PreToolUse added.
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)
}

func TestMergeNoChangeWhenAlreadyMerged(t *testing.T) {
	settings := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"_comment": "Generated by chunk init.",
		"permissions": {"allow": ["Bash(chunk:*)"]},
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "test", "timeout": 60}]}
			]
		}
	}`)

	result, err := Merge(settings, settings)
	assert.NilError(t, err)
	assert.Assert(t, !result.Changed)
}

func TestMergeGeneratedWithNoHooks(t *testing.T) {
	existing := []byte(`{
		"hooks": {
			"PreToolUse": [
				{"matcher": "Bash(git commit*)", "hooks": [{"type": "command", "command": "existing-cmd", "timeout": 30}]}
			]
		}
	}`)
	generated := []byte(`{
		"$schema": "https://json.schemastore.org/claude-code-settings.json",
		"permissions": {"allow": ["Bash(chunk:*)"]}
	}`)

	result, err := Merge(existing, generated)
	assert.NilError(t, err)

	var merged map[string]interface{}
	assert.NilError(t, json.Unmarshal(result.Merged, &merged))

	// Existing hooks preserved when generated has no hooks.
	hooks := merged["hooks"].(map[string]interface{})
	preToolUse := hooks["PreToolUse"].([]interface{})
	assert.Equal(t, len(preToolUse), 1)

	group := preToolUse[0].(map[string]interface{})
	hookEntries := group["hooks"].([]interface{})
	entry := hookEntries[0].(map[string]interface{})
	assert.Equal(t, entry["command"], "existing-cmd")
}

func TestDiffShowsChanges(t *testing.T) {
	original := []byte(`{
  "permissions": {
    "allow": ["Read"]
  }
}`)
	merged := []byte(`{
  "permissions": {
    "allow": ["Bash(chunk:*)", "Read"]
  }
}`)

	diff := Diff(original, merged)
	assert.Assert(t, diff != "", "expected non-empty diff")
	assert.Assert(t, strings.Contains(diff, "---"))
	assert.Assert(t, strings.Contains(diff, "+++"))
	assert.Assert(t, strings.Contains(diff, "Bash(chunk:*)"))
}

func TestDiffEmptyWhenIdentical(t *testing.T) {
	data := []byte(`{"foo": "bar"}`)
	diff := Diff(data, data)
	assert.Equal(t, diff, "")
}

func TestMergeMalformedExisting(t *testing.T) {
	_, err := Merge([]byte(`not json`), []byte(`{}`))
	assert.ErrorContains(t, err, "parse existing settings")
}

func TestMergeMalformedGenerated(t *testing.T) {
	_, err := Merge([]byte(`{}`), []byte(`not json`))
	assert.ErrorContains(t, err, "parse generated settings")
}
