package settings

import (
	"encoding/json"

	"github.com/CircleCI-Public/chunk-cli/internal/config"
)

// conflictsTimeout bounds the advisory conflict notice. It reads a precomputed
// answer over a Unix socket, so anything beyond a couple of seconds means the
// daemon is not answering — in which case the command prints nothing and the
// commit proceeds either way.
const conflictsTimeout = 5

// maxHookTimeout is Claude Code's maximum hook timeout, and the cap every
// generated timeout is held under. Codex has no documented maximum; it shares
// the cap so the two files agree on how long a gate may hold a commit.
const maxHookTimeout = 600

// Spinner text the agent shows while each hook runs. It is fixed when init
// writes the file, so it names the command being run and nothing decided at
// run time: whether the Stop hook hits the cache, skips a clean tree, or goes to
// the background is reported afterwards, through the hook's systemMessage.
const (
	stopStatusMessage      = "Running chunk validate"
	conflictsStatusMessage = "Running chunk conflicts before commit"
)

// commitStatusMessage is the spinner text for the commit gate. It says why the
// commit is waiting.
const commitStatusMessage = "Running chunk validate before commit"

// commitCommand is the commit gate: every configured command, run in sequence.
// One entry rather than one per command because the validate cache keys on the
// command name, so only a bare run shares a key with the Stop hook's. A commit
// of a tree the Stop hook already passed is then a cache hit instead of a
// second full run of everything.
const commitCommand = "cd ${CLAUDE_PROJECT_DIR:-.} && chunk validate"

// hookEntry is one hook command within a hook group.
type hookEntry struct {
	Type          string `json:"type"`
	If            string `json:"if,omitempty"`
	Command       string `json:"command"`
	Timeout       int    `json:"timeout"`
	StatusMessage string `json:"statusMessage,omitempty"`
}

// hookGroup is a group of hooks filtered by matcher.
// Matcher is omitted for hook types that don't use it (e.g. Stop).
type hookGroup struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// settingsJSON is the .claude/settings.json structure.
type settingsJSON struct {
	Schema      string                 `json:"$schema"`
	Comment     string                 `json:"_comment"`
	Permissions map[string][]string    `json:"permissions"`
	Hooks       map[string][]hookGroup `json:"hooks,omitempty"`
}

// codexHooksJSON is the .codex/hooks.json structure — hooks only, no metadata or permissions.
type codexHooksJSON struct {
	Hooks map[string][]hookGroup `json:"hooks,omitempty"`
}

// Build generates .claude/settings.json content from commands.
// It creates:
//   - A PreToolUse group on the Bash tool holding the advisory conflict notice
//     and the commit gate, both restricted to git commit by their "if".
//   - A Stop hook that runs "chunk validate" after every session.
func Build(commands []config.Command) ([]byte, error) {
	commitTimeout := 0
	for _, cmd := range commands {
		timeout := cmd.Timeout
		if timeout == 0 {
			timeout = 60
		}
		commitTimeout += timeout
	}
	hooks := []hookEntry{
		// The advisory notice goes first, so the agent has it before the gate can
		// stop the commit. Its timeout is short because it only reads an answer the
		// daemon computed earlier — it never previews a merge itself.
		{
			Type:          "command",
			If:            CommitIfFilter,
			Command:       ConflictsCommand,
			Timeout:       conflictsTimeout,
			StatusMessage: conflictsStatusMessage,
		},
		{
			Type:          "command",
			If:            CommitIfFilter,
			Command:       commitCommand,
			Timeout:       min(commitTimeout, maxHookTimeout),
			StatusMessage: commitStatusMessage,
		},
	}

	s := settingsJSON{
		Schema:  "https://json.schemastore.org/claude-code-settings.json",
		Comment: "Generated by chunk init.",
		Permissions: map[string][]string{
			"allow": {"Bash(chunk:*)"},
		},
	}

	// Gated on commands, not on len(hooks): the conflicts advisory is prepended
	// unconditionally, so a project with nothing to validate would otherwise get
	// a settings file whose Stop hook runs `chunk validate` with no commands to
	// run. An unconfigured project gets no hooks at all, advisory included.
	if len(commands) > 0 {
		// Compute a Stop hook timeout that covers all commands running sequentially.
		stopTimeout := 30 // base buffer
		for _, cmd := range commands {
			t := cmd.Timeout
			if t == 0 {
				t = 300
			}
			stopTimeout += t
		}
		stopTimeout = min(stopTimeout, maxHookTimeout)

		s.Hooks = map[string][]hookGroup{
			"PreToolUse": {
				{
					Matcher: CommitMatcher,
					Hooks:   hooks,
				},
			},
			// Stop hook: runs validation at session end.
			"Stop": {
				{
					Hooks: []hookEntry{
						{
							Type:          "command",
							Command:       StopCommand,
							Timeout:       stopTimeout,
							StatusMessage: stopStatusMessage,
						},
					},
				},
			},
		}
	}

	return json.MarshalIndent(s, "", "  ")
}

// codexCommitStatusMessage is the spinner text for the Codex commit gate. Codex
// cannot filter a hook on the command it is about to run, so the gate starts
// before every Bash call and exits at once for anything but a git commit.
// The text has to read right on both.
const codexCommitStatusMessage = "Running chunk validate if this is a commit"

// codexCommitCommand is the Codex commit gate: every configured command, run in
// sequence. Merge owns the entry by its CommitIfFilter, not by this string.
const codexCommitCommand = "chunk validate"

// BuildCodex generates .codex/hooks.json content from commands.
// Produces the same hook types as Build but without Claude Code-specific
// metadata ($schema, _comment), without a permissions block, and with the
// commit gate as a single entry:
//
//   - Codex launches every matching hook for an event concurrently, so one entry
//     per command would have a formatter rewriting files while lint and test
//     read them. A single `chunk validate` runs them in sequence instead.
//   - Codex has no per-entry "if", so the entry still carries CommitIfFilter
//     (it is how Merge recognises chunk's entries) but chunk validate does the
//     filtering itself, from the command in the hook payload.
//
// Commands run as-is. Codex runs hooks in the session's working directory,
// which may be a subdirectory of the project; chunk validate finds the project
// from there when it runs as a hook.
func BuildCodex(commands []config.Command) ([]byte, error) {
	s := codexHooksJSON{}
	if len(commands) == 0 {
		return json.MarshalIndent(s, "", "  ")
	}

	commitTimeout := 0
	for _, cmd := range commands {
		timeout := cmd.Timeout
		if timeout == 0 {
			timeout = 60
		}
		commitTimeout += timeout
	}
	commitTimeout = min(commitTimeout, maxHookTimeout)
	stopTimeout := min(30+commitTimeout, maxHookTimeout)

	s.Hooks = map[string][]hookGroup{
		"PreToolUse": {
			{
				Matcher: CommitMatcher,
				Hooks: []hookEntry{
					{
						Type:          "command",
						If:            CommitIfFilter,
						Command:       codexCommitCommand,
						Timeout:       commitTimeout,
						StatusMessage: codexCommitStatusMessage,
					},
				},
			},
		},
		"Stop": {
			{
				Hooks: []hookEntry{
					{
						Type:          "command",
						Command:       StopCommand,
						Timeout:       stopTimeout,
						StatusMessage: stopStatusMessage,
					},
				},
			},
		},
	}

	return json.MarshalIndent(s, "", "  ")
}
