package settings

import (
	"encoding/json"

	"github.com/CircleCI-Public/chunk-cli/internal/config"
)

// hookEntry is one hook command within a hook group.
type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
}

// hookGroup is a group of hooks filtered by matcher.
// Matcher is omitted for hook types that don't use it (e.g. Stop).
type hookGroup struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// settingsJSON is the .claude/settings.json structure.
type settingsJSON struct {
	Schema      string                 `json:"$schema"`
	Comment     string                 `json:"_comment"`
	Permissions map[string][]string    `json:"permissions"`
	Hooks       map[string][]hookGroup `json:"hooks,omitempty"`
}

// codexHooksJSON is the .codex/hooks.json structure — hooks only, no metadata or permissions.
type codexHooksJSON struct {
	Hooks map[string][]hookGroup `json:"hooks,omitempty"`
}

const (
	maxHookTimeout     = 600
	defaultCmdTimeout  = 300
	defaultFixTimeout  = 30
	baseValidateBuffer = 30
)

// validateTimeout computes a Stop hook timeout from the validate commands,
// capped at maxHookTimeout.
func validateTimeout(cmds []config.ValidateCommand) int {
	total := baseValidateBuffer
	for _, cmd := range cmds {
		t := cmd.Timeout
		if t == 0 {
			t = defaultCmdTimeout
		}
		total += t
	}
	if total > maxHookTimeout {
		return maxHookTimeout
	}
	return total
}

// fixTimeout returns a timeout for the chunk fix PostToolUse hook — sum of
// fix command timeouts, capped at maxHookTimeout.
func fixTimeout(cmds []config.FixCommand) int {
	total := 0
	for _, cmd := range cmds {
		t := cmd.Timeout
		if t == 0 {
			t = defaultFixTimeout
		}
		total += t
	}
	if total == 0 {
		return defaultFixTimeout
	}
	if total > maxHookTimeout {
		return maxHookTimeout
	}
	return total
}

// preToolUseHookEntry builds a single hook entry for the PreToolUse commit hook.
func preToolUseHookEntry(timeout int) hookEntry {
	return hookEntry{
		Type:    "command",
		Command: "cd ${CLAUDE_PROJECT_DIR:-.} && chunk validate",
		Timeout: timeout,
	}
}

// Build generates .claude/settings.json content.
//   - PreToolUse "Bash(git commit*)" runs chunk validate before commits.
//   - PostToolUse "Edit|Write" runs chunk fix after every file edit (only when fix commands exist).
func Build(fix []config.FixCommand, validate []config.ValidateCommand) ([]byte, error) {
	s := settingsJSON{
		Schema:  "https://json.schemastore.org/claude-code-settings.json",
		Comment: "Generated by chunk init.",
		Permissions: map[string][]string{
			"allow": {"Bash(chunk:*)"},
		},
	}

	if len(validate) > 0 || len(fix) > 0 {
		hooks := map[string][]hookGroup{}

		hooks["SessionStart"] = []hookGroup{
			{
				Hooks: []hookEntry{
					{
						Type:    "command",
						Command: "cd ${CLAUDE_PROJECT_DIR:-.} && chunk session start",
						Timeout: 5,
					},
				},
			},
		}

		if len(validate) > 0 {
			hooks["PreToolUse"] = []hookGroup{
				{
					Matcher: CommitMatcher,
					Hooks:   []hookEntry{preToolUseHookEntry(validateTimeout(validate))},
				},
			}
		}

		if len(fix) > 0 {
			hooks["PostToolUse"] = []hookGroup{
				{
					Matcher: FixMatcher,
					Hooks: []hookEntry{
						{
							Type:    "command",
							Command: "cd ${CLAUDE_PROJECT_DIR:-.} && chunk fix",
							Timeout: fixTimeout(fix),
						},
					},
				},
			}
		}

		s.Hooks = hooks
	}

	return json.MarshalIndent(s, "", "  ")
}

// BuildCodex generates .codex/hooks.json content.
// Produces the same hook structure as Build but without Claude Code-specific
// metadata ($schema, _comment) and without a permissions block. Commands run
// as-is; Codex sets CWD to the project root before invoking hooks.
func BuildCodex(fix []config.FixCommand, validate []config.ValidateCommand) ([]byte, error) {
	s := codexHooksJSON{}

	if len(validate) > 0 || len(fix) > 0 {
		hooks := map[string][]hookGroup{}

		if len(validate) > 0 {
			hooks["PreToolUse"] = []hookGroup{
				{
					Matcher: CommitMatcher,
					Hooks: []hookEntry{
						{
							Type:    "command",
							Command: "chunk validate",
							Timeout: validateTimeout(validate),
						},
					},
				},
			}
		}

		if len(fix) > 0 {
			hooks["PostToolUse"] = []hookGroup{
				{
					Matcher: FixMatcher,
					Hooks: []hookEntry{
						{
							Type:    "command",
							Command: "chunk fix",
							Timeout: fixTimeout(fix),
						},
					},
				},
			}
		}

		s.Hooks = hooks
	}

	return json.MarshalIndent(s, "", "  ")
}
