/**
 * Shell environment utilities for `chunk hook env update`.
 *
 * Handles ENV file generation (profile-based CHUNK_HOOK_* exports),
 * shell startup file detection, and idempotent sourcing block management.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { basename, dirname, join } from "node:path";
import { shellEnv } from "shell-env";

import { log } from "./log";

// ---------------------------------------------------------------------------
// Platform detection
// ---------------------------------------------------------------------------

/**
 * Escape a string for safe embedding inside single quotes in POSIX shell.
 * Single-quoted strings are fully literal except for the single quote itself,
 * which is handled by ending the string, escaping the quote, and reopening.
 */
export function shellQuote(s: string): string {
	return s.replace(/'/g, "'\\''");
}

/** Detect the current operating system. */
export function detectOS(): "macos" | "linux" {
	return platform() === "darwin" ? "macos" : "linux";
}

// ---------------------------------------------------------------------------
// Default paths
// ---------------------------------------------------------------------------

function xdgConfigBase(): string {
	return process.env.XDG_CONFIG_HOME || join(homedir(), ".config");
}

/** Default ENV file location. */
export function defaultEnvFile(): string {
	return join(xdgConfigBase(), "chunk", "hook", "env");
}

/** Legacy ENV file location (pre-XDG consolidation). */
export function legacyEnvFile(): string {
	return join(homedir(), ".config", "chunk-hook", "env");
}

/** Default log directory. */
export function defaultLogDir(): string {
	const os = detectOS();
	if (os === "macos") {
		return `${homedir()}/Library/Logs/chunk-hook`;
	}
	return `${homedir()}/.local/share/chunk-hook/logs`;
}

// ---------------------------------------------------------------------------
// Shell startup files
// ---------------------------------------------------------------------------

/**
 * Return the shell startup files for the current shell.
 *
 * Both login and interactive files are updated so config applies
 * to new terminal tabs/windows as well as interactive subshells.
 */
export function defaultShellStartupFiles(): string[] {
	const shell = basename(process.env.SHELL ?? "");
	const home = homedir();

	switch (shell) {
		case "zsh":
			return [`${home}/.zprofile`, `${home}/.zshrc`];
		case "bash": {
			const os = detectOS();
			const login = os === "macos" ? `${home}/.bash_profile` : `${home}/.profile`;
			return [login, `${home}/.bashrc`];
		}
		default:
			return [`${home}/.profile`];
	}
}

// ---------------------------------------------------------------------------
// Profile-based ENV content generation
// ---------------------------------------------------------------------------

/** Supported environment profiles. */
export type Profile = "disable" | "enable" | "tests-lint";

/** All valid profile names. */
export const PROFILES: Profile[] = ["disable", "enable", "tests-lint"];

/** Options for ENV content generation. */
export type EnvContentOptions = {
	profile: Profile;
	logDir: string;
	verbose: boolean;
	projectRoot?: string;
	envFile: string;
};

/**
 * Generate the content for the chunk-hook ENV file.
 *
 * The generated file is sourced from shell startup files and exports
 * CHUNK_HOOK_* environment variables based on the selected profile.
 */
export function generateEnvContent(opts: EnvContentOptions): string {
	const lines: string[] = [];

	lines.push("# chunk-hook environment configuration");
	lines.push(`# Generated by \`chunk hook env update\` on ${new Date().toISOString()}`);
	lines.push("#");
	lines.push("# This file is sourced from your shell startup files (e.g. ~/.zprofile, ~/.zshrc).");
	lines.push("# Edit directly or re-run: chunk hook env update --profile <name>");
	lines.push("#");
	lines.push("# Quick toggle examples:");
	lines.push(`#   Enable all:        echo 'CHUNK_HOOK_ENABLE=1' > ${opts.envFile}`);
	lines.push(`#   Disable all:       echo 'CHUNK_HOOK_ENABLE=0' > ${opts.envFile}`);
	lines.push(
		"#   Enable tests only: printf 'CHUNK_HOOK_ENABLE=0\\nCHUNK_HOOK_ENABLE_TESTS=1\\n" +
			`CHUNK_HOOK_ENABLE_TESTS_CHANGED=1\\n' > ${opts.envFile}`,
	);
	lines.push("");

	switch (opts.profile) {
		case "disable":
			lines.push("# Profile: disable — all hooks disabled");
			lines.push("export CHUNK_HOOK_ENABLE=0");
			break;
		case "enable":
			lines.push("# Profile: enable — all hooks enabled");
			lines.push("export CHUNK_HOOK_ENABLE=1");
			break;
		case "tests-lint":
			lines.push("# Profile: tests-lint — tests and lint enabled");
			lines.push("export CHUNK_HOOK_ENABLE=0");
			lines.push("export CHUNK_HOOK_ENABLE_TESTS=1");
			lines.push("export CHUNK_HOOK_ENABLE_TESTS_CHANGED=1");
			lines.push("export CHUNK_HOOK_ENABLE_LINT=1");
			break;
	}

	lines.push("");
	lines.push("# Logging");
	lines.push(`export CHUNK_HOOK_LOG_DIR='${shellQuote(opts.logDir)}'`);
	if (opts.verbose) {
		lines.push("export CHUNK_HOOK_VERBOSE=1");
	} else {
		lines.push("# export CHUNK_HOOK_VERBOSE=1  # uncomment to enable verbose logging");
	}

	lines.push("");
	lines.push("# Multi-repo: parent directory for --project name resolution");
	lines.push("# Set this to the directory containing your repo checkouts.");
	if (opts.projectRoot) {
		lines.push(`export CHUNK_HOOK_PROJECT_ROOT='${shellQuote(opts.projectRoot)}'`);
	} else {
		// biome-ignore lint/suspicious/noTemplateCurlyInString: this is shell code, not JS template literal
		lines.push('# export CHUNK_HOOK_PROJECT_ROOT="${HOME}/workspace"');
	}

	lines.push("");
	return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Idempotent managed-block upsert for shell startup files
// ---------------------------------------------------------------------------

/**
 * Upsert a managed two-line block in a shell startup file.
 *
 * If `markerLine` already exists, the marker + the line immediately following
 * it are replaced with `markerLine` + `valueLine`. If the marker doesn't
 * exist, the block is appended.
 */
export function upsertManagedBlock(filePath: string, markerLine: string, valueLine: string): void {
	if (!existsSync(filePath)) {
		// Create the file with the block
		const dir = dirname(filePath);
		mkdirSync(dir, { recursive: true });
		writeFileSync(filePath, `\n${markerLine}\n${valueLine}\n`);
		return;
	}

	const content = readFileSync(filePath, "utf-8");
	const lines = content.split("\n");
	const result: string[] = [];
	let found = false;
	let skipNext = false;

	for (const line of lines) {
		if (skipNext) {
			skipNext = false;
			continue;
		}

		if (line === markerLine) {
			result.push(markerLine);
			result.push(valueLine);
			found = true;
			skipNext = true;
			continue;
		}

		result.push(line);
	}

	if (!found) {
		// Ensure there's a blank line before the block if file doesn't end with one
		if (result.length > 0 && result[result.length - 1] !== "") {
			result.push("");
		}
		result.push(markerLine);
		result.push(valueLine);
	}

	writeFileSync(filePath, result.join("\n"));
}

// ---------------------------------------------------------------------------
// Ensure ENV is sourced in shell startup files
// ---------------------------------------------------------------------------

const ENV_MARKER = "# chunk-hook env";

/**
 * Ensure that the ENV file is sourced in all relevant shell startup files.
 *
 * Adds (or updates) a two-line block:
 *   # chunk-hook env
 *   if [ -f "<envFile>" ]; then . "<envFile>"; fi
 *
 * @param envFile - Path to the ENV file to source.
 * @param overrideFiles - Override shell startup files (for testing). When omitted, uses auto-detected defaults.
 */
export function ensureLoginSourcing(
	envFile: string,
	overrideFiles?: string[],
	dryRun?: boolean,
): string[] {
	const startupFiles = overrideFiles ?? defaultShellStartupFiles();
	const sourceLine = `if [ -f '${shellQuote(envFile)}' ]; then . '${shellQuote(envFile)}'; fi`;
	const updated: string[] = [];

	for (const file of startupFiles) {
		if (!dryRun) {
			upsertManagedBlock(file, ENV_MARKER, sourceLine);
		}
		updated.push(file);
	}

	return updated;
}

// ---------------------------------------------------------------------------
// Write ENV file
// ---------------------------------------------------------------------------

/**
 * Write the ENV file with the given profile configuration.
 * Creates the parent directory if needed.
 *
 * @returns true if the file already existed (was overwritten).
 */
export function writeEnvFile(envFile: string, content: string): boolean {
	const existed = existsSync(envFile);
	const dir = dirname(envFile);
	mkdirSync(dir, { recursive: true });
	writeFileSync(envFile, content);
	return existed;
}

// ---------------------------------------------------------------------------
// Clean shell environment for exec commands
// ---------------------------------------------------------------------------

let cachedCleanEnv: Promise<Record<string, string>> | undefined;

/**
 * Return a clean login-shell environment, free of variables injected by the
 * parent process (e.g. `AGENT_MODE`, `CLAUDE_*`).
 *
 * The promise is cached for the lifetime of the process so the shell is only
 * spawned once — concurrent callers share the same in-flight request.
 * On failure the current `process.env` is returned as a fallback so commands
 * still run.
 */
export function getCleanEnv(): Promise<Record<string, string>> {
	if (cachedCleanEnv) return cachedCleanEnv;

	cachedCleanEnv = shellEnv().catch((err) => {
		log("shell-env", `Failed to read login-shell env, falling back to process.env: ${err}`);
		// Fallback: copy process.env (strip undefineds)
		return Object.fromEntries(
			Object.entries(process.env).filter((e): e is [string, string] => e[1] !== undefined),
		);
	});

	return cachedCleanEnv;
}
