package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"github.com/CircleCI-Public/chunk-cli/internal/iostream"
	"github.com/CircleCI-Public/chunk-cli/internal/ui"
)

// EnvUpdateOptions holds options for the env update command.
type EnvUpdateOptions struct {
	Profile      string
	EnvFile      string
	LogDir       string
	Verbose      bool
	ProjectRoot  string
	StartupFiles []string // override shell startup files (for testing)
}

// RunEnvUpdate writes the env file with profile-based configuration,
// ensures shell startup files source it, and migrates legacy paths.
func RunEnvUpdate(opts EnvUpdateOptions, streams iostream.Streams) error {
	if opts.Profile == "" {
		opts.Profile = ProfileEnable
	}
	if err := ValidateProfile(opts.Profile); err != nil {
		return err
	}

	if opts.EnvFile == "" {
		opts.EnvFile = defaultEnvFile()
	}
	if opts.LogDir == "" {
		opts.LogDir = defaultLogDir()
	}

	// Migrate legacy env file if using the default path.
	if opts.EnvFile == defaultEnvFile() {
		migrateEnvFile(opts.EnvFile, legacyEnvFile())
	}

	// Create log directory.
	if err := os.MkdirAll(opts.LogDir, 0o755); err != nil {
		return fmt.Errorf("create log dir: %w", err)
	}

	// Generate and write env file.
	content := generateEnvContent(opts)
	dir := filepath.Dir(opts.EnvFile)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create env dir: %w", err)
	}
	if err := os.WriteFile(opts.EnvFile, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	// Ensure shell startup files source the env file.
	ensureLoginSourcing(opts.EnvFile, opts.StartupFiles)

	streams.ErrPrintln(ui.Success("Configuration complete"))
	return nil
}

func defaultEnvFile() string {
	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg == "" {
		home, _ := os.UserHomeDir()
		xdg = filepath.Join(home, ".config")
	}
	return filepath.Join(xdg, "chunk", "hook", "env")
}

func legacyEnvFile() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "chunk-hook", "env")
}

func defaultLogDir() string {
	home, _ := os.UserHomeDir()
	if runtime.GOOS == "darwin" {
		return filepath.Join(home, "Library", "Logs", "chunk-hook")
	}
	return filepath.Join(home, ".local", "share", "chunk-hook", "logs")
}

// migrateEnvFile moves a legacy env file to the new location.
// If the new file already exists or the legacy file doesn't exist, this is a no-op.
func migrateEnvFile(newFile, legacy string) {
	if legacy == newFile {
		return
	}
	if _, err := os.Stat(legacy); os.IsNotExist(err) {
		return
	}
	if _, err := os.Stat(newFile); err == nil {
		return // new file already exists
	}

	dir := filepath.Dir(newFile)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	if err := os.Rename(legacy, newFile); err != nil {
		return
	}
	// Try to remove the now-empty legacy directory.
	_ = os.Remove(filepath.Dir(legacy))
}

func generateEnvContent(opts EnvUpdateOptions) string {
	var content string

	content += "# chunk-hook environment configuration\n"
	content += fmt.Sprintf("# Generated by `chunk hook env update` on %s\n", time.Now().UTC().Format(time.RFC3339))
	content += "#\n"
	content += "# This file is sourced from your shell startup files (e.g. ~/.zprofile, ~/.zshrc).\n"
	content += "# Edit directly or re-run: chunk hook env update --profile <name>\n"
	content += "#\n"
	content += "# Quick toggle examples:\n"
	content += fmt.Sprintf("#   Enable all:        echo 'CHUNK_HOOK_ENABLE=1' > %s\n", opts.EnvFile)
	content += fmt.Sprintf("#   Disable all:       echo 'CHUNK_HOOK_ENABLE=0' > %s\n", opts.EnvFile)
	content += fmt.Sprintf("#   Enable tests only: printf 'CHUNK_HOOK_ENABLE=0\\nCHUNK_HOOK_ENABLE_TESTS=1\\nCHUNK_HOOK_ENABLE_TESTS_CHANGED=1\\n' > %s\n", opts.EnvFile)
	content += "\n"

	switch opts.Profile {
	case "disable":
		content += "# Profile: disable — all hooks disabled\n"
		content += "export CHUNK_HOOK_ENABLE=0\n"
	case ProfileEnable:
		content += "# Profile: enable — all hooks enabled\n"
		content += "export CHUNK_HOOK_ENABLE=1\n"
	case "tests-lint":
		content += "# Profile: tests-lint — tests and lint enabled\n"
		content += "export CHUNK_HOOK_ENABLE=0\n"
		content += "export CHUNK_HOOK_ENABLE_TESTS=1\n"
		content += "export CHUNK_HOOK_ENABLE_TESTS_CHANGED=1\n"
		content += "export CHUNK_HOOK_ENABLE_LINT=1\n"
	}

	content += "\n"
	content += "# Logging\n"
	content += fmt.Sprintf("export CHUNK_HOOK_LOG_DIR='%s'\n", shellQuote(opts.LogDir))
	if opts.Verbose {
		content += "export CHUNK_HOOK_VERBOSE=1\n"
	} else {
		content += "# export CHUNK_HOOK_VERBOSE=1  # uncomment to enable verbose logging\n"
	}

	content += "\n"
	content += "# Multi-repo: parent directory for --project name resolution\n"
	content += "# Set this to the directory containing your repo checkouts.\n"
	if opts.ProjectRoot != "" {
		content += fmt.Sprintf("export CHUNK_HOOK_PROJECT_ROOT='%s'\n", shellQuote(opts.ProjectRoot))
	} else {
		content += "# export CHUNK_HOOK_PROJECT_ROOT=\"${HOME}/workspace\"\n"
	}

	content += "\n"
	return content
}
