package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	"github.com/CircleCI-Public/chunk-cli/internal/iostream"
	"github.com/CircleCI-Public/chunk-cli/internal/ui"
)

// EnvUpdateOptions holds options for the env update command.
type EnvUpdateOptions struct {
	Profile     string
	EnvFile     string
	LogDir      string
	Verbose     bool
	ProjectRoot string
}

// RunEnvUpdate writes the env file with profile-based configuration.
func RunEnvUpdate(opts EnvUpdateOptions, streams iostream.Streams) error {
	if opts.Profile == "" {
		opts.Profile = "enable"
	}
	if err := ValidateProfile(opts.Profile); err != nil {
		return err
	}

	if opts.EnvFile == "" {
		opts.EnvFile = defaultEnvFile()
	}
	if opts.LogDir == "" {
		opts.LogDir = defaultLogDir()
	}

	// Create log directory
	if err := os.MkdirAll(opts.LogDir, 0o755); err != nil {
		return fmt.Errorf("create log dir: %w", err)
	}

	// Generate and write env file
	content := generateEnvContent(opts)
	dir := filepath.Dir(opts.EnvFile)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create env dir: %w", err)
	}
	if err := os.WriteFile(opts.EnvFile, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write env file: %w", err)
	}

	streams.ErrPrintln(ui.Success("Configuration complete"))
	return nil
}

func defaultEnvFile() string {
	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg == "" {
		home, _ := os.UserHomeDir()
		xdg = filepath.Join(home, ".config")
	}
	return filepath.Join(xdg, "chunk", "hook", "env")
}

func defaultLogDir() string {
	home, _ := os.UserHomeDir()
	if runtime.GOOS == "darwin" {
		return filepath.Join(home, "Library", "Logs", "chunk-hook")
	}
	return filepath.Join(home, ".local", "share", "chunk-hook", "logs")
}

func generateEnvContent(opts EnvUpdateOptions) string {
	var content string

	content += "# chunk-hook environment configuration\n"
	content += fmt.Sprintf("# Generated by `chunk hook env update` on %s\n", time.Now().UTC().Format(time.RFC3339))
	content += "#\n"
	content += "# This file is sourced from your shell startup files.\n"
	content += "\n"

	switch opts.Profile {
	case "disable":
		content += "# Profile: disable — all hooks disabled\n"
		content += "export CHUNK_HOOK_ENABLE=0\n"
	case "enable":
		content += "# Profile: enable — all hooks enabled\n"
		content += "export CHUNK_HOOK_ENABLE=1\n"
	case "tests-lint":
		content += "# Profile: tests-lint — tests and lint enabled\n"
		content += "export CHUNK_HOOK_ENABLE=0\n"
		content += "export CHUNK_HOOK_ENABLE_TESTS=1\n"
		content += "export CHUNK_HOOK_ENABLE_TESTS_CHANGED=1\n"
		content += "export CHUNK_HOOK_ENABLE_LINT=1\n"
	}

	content += "\n"
	content += "# Logging\n"
	content += fmt.Sprintf("export CHUNK_HOOK_LOG_DIR='%s'\n", opts.LogDir)
	if opts.Verbose {
		content += "export CHUNK_HOOK_VERBOSE=1\n"
	}

	content += "\n"
	if opts.ProjectRoot != "" {
		content += fmt.Sprintf("export CHUNK_HOOK_PROJECT_ROOT='%s'\n", opts.ProjectRoot)
	}

	content += "\n"
	return content
}
