package hook

// templateFile describes a file to copy during repo init.
type templateFile struct {
	relativePath      string
	content           string
	substituteProject bool
}

var templateFiles = []templateFile{
	{
		relativePath:      ".chunk/hook/.gitignore",
		content:           gitignoreTemplate,
		substituteProject: false,
	},
	{
		relativePath:      ".chunk/hook/config.yml",
		content:           configYMLTemplate,
		substituteProject: false,
	},
	{
		relativePath:      ".claude/settings.json",
		content:           settingsJSONTemplate,
		substituteProject: true,
	},
}

const gitignoreTemplate = `# chunk hook runtime files (not committed)
.chunk-hook-active
`

const configYMLTemplate = `# .chunk/hook/config.yml — Per-repo configuration for chunk hook.
#
# Place this file at ` + "`.chunk/hook/config.yml`" + ` in your project root.
# Edit the ` + "`command:`" + ` fields below to match your repo's tooling.

# --- Named trigger groups ---
triggers:
  pre-commit:
    - "git commit"
    - "git push"

# --- Exec definitions ---
execs:
  tests:
    command: ""
    fileExt: ""
    always: false
    timeout: 300
    limit: 3

  tests-changed:
    command: ""
    fileExt: ""
    always: false
    timeout: 300
    limit: 3

  lint:
    command: ""
    always: false
    timeout: 60
    limit: 3
`

const settingsJSONTemplate = `{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "_comment": "Generated by chunk hook repo init. Hooks for tests and lint.",
  "permissions": {
    "allow": [
      "Bash(chunk:*)"
    ]
  },
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook scope deactivate --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook state append --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook exec check tests-changed --on pre-commit --matcher 'Bash|Shell|run_in_terminal' --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 10
          },
          {
            "type": "command",
            "command": "chunk hook exec run lint --on pre-commit --matcher 'Bash|Shell|run_in_terminal' --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 60
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook exec check tests --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 10
          },
          {
            "type": "command",
            "command": "chunk hook exec run lint --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 60
          }
        ]
      }
    ],
    "SessionEnd": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook scope deactivate --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          },
          {
            "type": "command",
            "command": "chunk hook state clear --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ]
  }
}
`
