package hook

// templateFile describes a file to copy during repo init.
type templateFile struct {
	relativePath      string
	content           string
	substituteProject bool
}

var templateFiles = []templateFile{
	{
		relativePath:      ".chunk/hook/.gitignore",
		content:           gitignoreTemplate,
		substituteProject: false,
	},
	{
		relativePath:      ".claude/settings.json",
		content:           settingsJSONTemplate,
		substituteProject: true,
	},
}

const gitignoreTemplate = `# chunk hook runtime files (not committed)
.chunk-hook-active
`

const settingsJSONTemplate = `{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "_comment": "Generated by chunk init. Hooks for tests and lint.",
  "permissions": {
    "allow": [
      "Bash(chunk:*)"
    ]
  },
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook scope deactivate --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook state append --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "chunk validate tests-changed --check --on pre-commit --matcher 'Bash|Shell|run_in_terminal' --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 10
          },
          {
            "type": "command",
            "command": "chunk validate lint --no-check --on pre-commit --matcher 'Bash|Shell|run_in_terminal' --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 60
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk validate tests --check --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 10
          },
          {
            "type": "command",
            "command": "chunk validate lint --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 60
          }
        ]
      }
    ],
    "SessionEnd": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "chunk hook scope deactivate --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          },
          {
            "type": "command",
            "command": "chunk hook state clear --project ${CLAUDE_PROJECT_DIR:-__PROJECT__}",
            "timeout": 5
          }
        ]
      }
    ]
  }
}
`
