package hook

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/CircleCI-Public/chunk-cli/internal/config"
)

// templateFile describes a file to copy during repo init.
type templateFile struct {
	relativePath      string
	content           string
	substituteProject bool
}

var templateFiles = []templateFile{
	{
		relativePath:      ".chunk/hook/.gitignore",
		content:           gitignoreTemplate,
		substituteProject: false,
	},
}

const gitignoreTemplate = `# chunk hook runtime files (not committed)
.chunk-hook-active
`

// hookEntry is one hook command within a hook group.
type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
}

// hookGroup is a group of hooks, optionally filtered by matcher.
type hookGroup struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// orderedEntry is a key-value pair for ordered JSON serialization.
type orderedEntry struct {
	Key   string
	Value []hookGroup
}

// settingsJSON is the top-level .claude/settings.json structure.
type settingsJSON struct {
	Schema      string              `json:"$schema"`
	Comment     string              `json:"_comment"`
	Env         map[string]string   `json:"env,omitempty"`
	Permissions map[string][]string `json:"permissions"`
	HookOrder   []orderedEntry      `json:"-"` // serialized manually
}

// MarshalJSON produces ordered hooks output.
func (s settingsJSON) MarshalJSON() ([]byte, error) {
	// Build hooks as ordered JSON manually
	var hookParts []string
	for _, entry := range s.HookOrder {
		val, err := json.MarshalIndent(entry.Value, "    ", "  ")
		if err != nil {
			return nil, err
		}
		hookParts = append(hookParts, fmt.Sprintf("    %q: %s", entry.Key, val))
	}

	// json.MarshalIndent on map[string]string and map[string][]string sorts keys
	// alphabetically (Go 1.12+), so output is deterministic.
	perms, _ := json.MarshalIndent(s.Permissions, "  ", "  ")

	var envBlock string
	if len(s.Env) > 0 {
		envJSON, _ := json.MarshalIndent(s.Env, "  ", "  ")
		envBlock = fmt.Sprintf(",\n  \"env\": %s", envJSON)
	}

	var hooksBlock string
	if len(hookParts) > 0 {
		hooksBlock = fmt.Sprintf(",\n  \"hooks\": {\n%s\n  }", strings.Join(hookParts, ",\n"))
	}

	return []byte(fmt.Sprintf(`{
  "$schema": %q,
  "_comment": %q,
  "permissions": %s%s%s
}`, s.Schema, s.Comment, perms, envBlock, hooksBlock)), nil
}

// inferRole returns the effective role for a command, falling back to
// name-based heuristics when the Role field is empty (legacy configs).
func inferRole(cmd config.Command) string {
	if cmd.Role != "" {
		return cmd.Role
	}
	if strings.HasSuffix(cmd.Name, "-changed") {
		return config.RolePrecheck
	}
	if cmd.Always {
		return config.RoleAutofix
	}
	return config.RoleGate
}

// hookTimeout returns a reasonable hook timeout for the command.
// For --check calls that just read a sentinel, use a short timeout.
// For --no-check calls that run the command, use the command's configured timeout.
func hookTimeout(cmd config.Command, isCheck bool) int {
	if isCheck {
		return 10
	}
	if cmd.Timeout > 0 {
		return cmd.Timeout
	}
	return 60
}

// projectVar returns the shell variable expression for the project directory.
func projectVar(projectName string) string {
	return fmt.Sprintf("${CLAUDE_PROJECT_DIR:-%s}", projectName)
}

// BuildSettingsJSON generates the .claude/settings.json content from detected commands.
func BuildSettingsJSON(projectName string, commands []config.Command) string {
	proj := projectVar(projectName)

	settings := settingsJSON{
		Schema:  "https://json.schemastore.org/claude-code-settings.json",
		Comment: "Generated by chunk init. Hooks for tests and lint.",
		Env:     map[string]string{"CHUNK_HOOK_ENABLE": "1"},
		Permissions: map[string][]string{
			"allow": {"Bash(chunk:*)"},
		},
	}

	// Infrastructure hooks (always present, in lifecycle order)
	settings.HookOrder = append(settings.HookOrder, orderedEntry{
		Key: "SessionStart",
		Value: []hookGroup{{
			Hooks: []hookEntry{{
				Type:    "command",
				Command: fmt.Sprintf("chunk hook scope deactivate --project %s", proj),
				Timeout: 5,
			}},
		}},
	})

	settings.HookOrder = append(settings.HookOrder, orderedEntry{
		Key: "UserPromptSubmit",
		Value: []hookGroup{{
			Hooks: []hookEntry{{
				Type:    "command",
				Command: fmt.Sprintf("chunk hook state append --project %s", proj),
				Timeout: 5,
			}},
		}},
	})

	// Build command hooks from detected commands
	var preToolHooks []hookEntry
	var stopHooks []hookEntry

	for _, cmd := range commands {
		role := inferRole(cmd)
		switch role {
		case config.RolePrecheck:
			// PreToolUse only: --check (fast sentinel read with trigger scoping).
			// Precheck commands are not added to Stop — the full variant (gate)
			// covers enforcement there.
			preToolHooks = append(preToolHooks, hookEntry{
				Type:    "command",
				Command: fmt.Sprintf("chunk validate %s --check --on pre-commit --project %s", cmd.Name, proj),
				Timeout: hookTimeout(cmd, true),
			})

		case config.RoleAutofix:
			// PreToolUse: --no-check (fire-and-forget, record sentinel)
			preToolHooks = append(preToolHooks, hookEntry{
				Type:    "command",
				Command: fmt.Sprintf("chunk validate %s --no-check --on pre-commit --project %s", cmd.Name, proj),
				Timeout: hookTimeout(cmd, false),
			})
			// Stop: --check --allow-missing
			stopHooks = append(stopHooks, hookEntry{
				Type:    "command",
				Command: fmt.Sprintf("chunk validate %s --check --allow-missing --project %s", cmd.Name, proj),
				Timeout: hookTimeout(cmd, true),
			})

		case config.RoleGate:
			// PreToolUse: --no-check (fire-and-forget, record sentinel)
			preToolHooks = append(preToolHooks, hookEntry{
				Type:    "command",
				Command: fmt.Sprintf("chunk validate %s --no-check --on pre-commit --project %s", cmd.Name, proj),
				Timeout: hookTimeout(cmd, false),
			})
			// Stop: --check --allow-missing
			stopHooks = append(stopHooks, hookEntry{
				Type:    "command",
				Command: fmt.Sprintf("chunk validate %s --check --allow-missing --project %s", cmd.Name, proj),
				Timeout: hookTimeout(cmd, true),
			})
		}
	}

	if len(preToolHooks) > 0 {
		settings.HookOrder = append(settings.HookOrder, orderedEntry{
			Key: "PreToolUse",
			Value: []hookGroup{{
				Matcher: "*",
				Hooks:   preToolHooks,
			}},
		})
	}

	if len(stopHooks) > 0 {
		settings.HookOrder = append(settings.HookOrder, orderedEntry{
			Key: "Stop",
			Value: []hookGroup{{
				Hooks: stopHooks,
			}},
		})
	}

	settings.HookOrder = append(settings.HookOrder, orderedEntry{
		Key: "SessionEnd",
		Value: []hookGroup{{
			Hooks: []hookEntry{
				{
					Type:    "command",
					Command: fmt.Sprintf("chunk hook scope deactivate --project %s", proj),
					Timeout: 5,
				},
				{
					Type:    "command",
					Command: fmt.Sprintf("chunk hook state clear --project %s", proj),
					Timeout: 5,
				},
			},
		}},
	})

	data, _ := json.MarshalIndent(settings, "", "  ")
	return string(data) + "\n"
}
