package sshterm

import (
	"context"
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"

	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/x/vt"
	"golang.org/x/crypto/ssh"

	"github.com/CircleCI-Public/chunk-cli/internal/sidecar"
)

// Model is a bubbletea component that renders an SSH PTY session via a VT emulator.
type Model struct {
	session *sidecar.Session
	cmd     string
	envVars map[string]string

	emulator *vt.Emulator
	conn     *sidecar.SSHConn
	sshSess  *ssh.Session
	stdin    io.WriteCloser
	stdout   io.Reader

	width    int
	height   int
	focused  bool
	err      error
	done     bool
	respDone chan struct{}
}

// New creates a Model. Call Init() to start the SSH connection.
// The terminal starts focused by default.
func New(session *sidecar.Session, cmd string, envVars map[string]string, width, height int) Model {
	return Model{
		session:  session,
		cmd:      cmd,
		envVars:  envVars,
		emulator: vt.NewEmulator(width, height),
		width:    width,
		height:   height,
		focused:  true,
		respDone: make(chan struct{}),
	}
}

// SetFocused updates keyboard focus without starting a new connection.
func (m Model) SetFocused(f bool) Model {
	m.focused = f
	return m
}

// Done reports whether the remote session has ended.
func (m Model) Done() bool { return m.done }

// Connected reports whether the SSH session is active.
func (m Model) Connected() bool { return m.conn != nil && !m.done }

// CursorPosition returns the cursor's current position within the terminal.
func (m Model) CursorPosition() (x, y int) {
	pos := m.emulator.CursorPosition()
	return pos.X, pos.Y
}

// Close tears down the SSH session and connection.
func (m Model) Close() {
	if m.respDone != nil {
		select {
		case <-m.respDone:
		default:
			close(m.respDone)
		}
	}
	_ = m.emulator.Close()
	if m.stdin != nil {
		_ = m.stdin.Close()
	}
	if m.sshSess != nil {
		_ = m.sshSess.Close()
	}
	if m.conn != nil {
		_ = m.conn.Close()
	}
}

type outputMsg struct{ data []byte }
type connectedMsg struct {
	conn   *sidecar.SSHConn
	sess   *ssh.Session
	stdin  io.WriteCloser
	stdout io.Reader
}
type disconnectedMsg struct{ err error }

// Init dials the SSH connection asynchronously.
func (m Model) Init() (Model, tea.Cmd) {
	return m, connect(m.session, m.cmd, m.envVars, m.width, m.height)
}

// envCmd prepends "env KEY=VALUE ..." to cmd so that env vars are injected
// without relying on SSH Setenv, which many servers reject.
func envCmd(cmd string, envVars map[string]string) string {
	if len(envVars) == 0 {
		return cmd
	}
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var parts []string
	for _, k := range keys {
		parts = append(parts, k+"="+sidecar.ShellEscape(envVars[k]))
	}
	return "env " + strings.Join(parts, " ") + " " + cmd
}

func connect(session *sidecar.Session, cmd string, envVars map[string]string, w, h int) tea.Cmd {
	return func() tea.Msg {
		conn, err := sidecar.DialSSH(context.Background(), session)
		if err != nil {
			return disconnectedMsg{err: err}
		}
		sess, err := conn.NewSession()
		if err != nil {
			_ = conn.Close()
			return disconnectedMsg{err: fmt.Errorf("ssh session: %w", err)}
		}
		if err := sess.RequestPty("xterm-256color", h, w, ssh.TerminalModes{
			ssh.ECHO:          1,
			ssh.TTY_OP_ISPEED: 14400,
			ssh.TTY_OP_OSPEED: 14400,
		}); err != nil {
			_ = sess.Close()
			_ = conn.Close()
			return disconnectedMsg{err: fmt.Errorf("request PTY: %w", err)}
		}
		stdout, err := sess.StdoutPipe()
		if err != nil {
			_ = sess.Close()
			_ = conn.Close()
			return disconnectedMsg{err: fmt.Errorf("stdout pipe: %w", err)}
		}
		stdin, err := sess.StdinPipe()
		if err != nil {
			_ = sess.Close()
			_ = conn.Close()
			return disconnectedMsg{err: fmt.Errorf("stdin pipe: %w", err)}
		}
		if err := sess.Start(envCmd(cmd, envVars)); err != nil {
			_ = sess.Close()
			_ = conn.Close()
			return disconnectedMsg{err: fmt.Errorf("start %s: %w", cmd, err)}
		}
		return connectedMsg{conn: conn, sess: sess, stdin: stdin, stdout: stdout}
	}
}

func readOutput(r io.Reader) tea.Cmd {
	return func() tea.Msg {
		buf := make([]byte, 4096)
		n, err := r.Read(buf)
		if n > 0 {
			data := make([]byte, n)
			copy(data, buf[:n])
			return outputMsg{data: data}
		}
		if err != nil {
			return disconnectedMsg{err: err}
		}
		return nil
	}
}

// forwardEmulatorResponses reads terminal query responses generated by the VT
// emulator (e.g. DA1/DA2 device attributes, CPR cursor position reports, mode
// reports) and writes them to SSH stdin so the remote process receives them.
// This MUST run concurrently with emulator.Write() because io.Pipe is
// synchronous: the emulator blocks on writing its response until this goroutine
// drains the read side.
func forwardEmulatorResponses(emulator *vt.Emulator, stdin io.WriteCloser, done <-chan struct{}) {
	buf := make([]byte, 4096)
	for {
		n, err := emulator.Read(buf)
		if n > 0 {
			_, _ = stdin.Write(buf[:n])
		}
		if err != nil {
			return
		}
		select {
		case <-done:
			return
		default:
		}
	}
}

// Update processes bubbletea messages.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	switch msg := msg.(type) {
	case connectedMsg:
		m.conn = msg.conn
		m.sshSess = msg.sess
		m.stdin = msg.stdin
		m.stdout = msg.stdout
		go forwardEmulatorResponses(m.emulator, m.stdin, m.respDone)
		return m, readOutput(m.stdout)

	case outputMsg:
		_, _ = m.emulator.Write(msg.data)
		return m, readOutput(m.stdout)

	case disconnectedMsg:
		if msg.err != nil && !errors.Is(msg.err, io.EOF) {
			m.err = msg.err
		}
		m.done = true
		return m, nil

	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
		m.emulator.Resize(msg.Width, msg.Height)
		if m.sshSess != nil {
			_ = m.sshSess.WindowChange(msg.Height, msg.Width)
		}
		return m, nil

	case tea.KeyPressMsg:
		if !m.focused || m.stdin == nil {
			return m, nil
		}
		if b := keyToBytes(tea.Key(msg)); len(b) > 0 {
			if _, err := m.stdin.Write(b); err != nil {
				m.err = fmt.Errorf("stdin write: %w", err)
				m.done = true
			}
		}
		return m, nil
	}
	return m, nil
}

// View renders the current VT emulator state.
func (m Model) View() string {
	if m.err != nil {
		return fmt.Sprintf("terminal error: %v", m.err)
	}
	if m.conn == nil {
		return "connecting..."
	}
	return m.emulator.Render()
}

// keyToBytes converts a bubbletea key event to the bytes an xterm-256color
// terminal would send for that key.
func keyToBytes(k tea.Key) []byte {
	// Ctrl+letter: map to control codes 0x01–0x1A
	if k.Mod == tea.ModCtrl {
		if k.Code >= 'a' && k.Code <= 'z' {
			return []byte{byte(k.Code - 'a' + 1)}
		}
		if k.Code >= 'A' && k.Code <= 'Z' {
			return []byte{byte(k.Code - 'A' + 1)}
		}
	}
	// Printable text
	if k.Text != "" {
		return []byte(k.Text)
	}
	switch k.Code {
	case tea.KeyEnter:
		return []byte{'\r'}
	case tea.KeyBackspace:
		return []byte{127}
	case tea.KeyTab:
		return []byte{'\t'}
	case tea.KeyEscape:
		return []byte{27}
	case tea.KeyUp:
		return []byte{27, '[', 'A'}
	case tea.KeyDown:
		return []byte{27, '[', 'B'}
	case tea.KeyRight:
		return []byte{27, '[', 'C'}
	case tea.KeyLeft:
		return []byte{27, '[', 'D'}
	case tea.KeyHome:
		return []byte{27, '[', 'H'}
	case tea.KeyEnd:
		return []byte{27, '[', 'F'}
	case tea.KeyPgUp:
		return []byte{27, '[', '5', '~'}
	case tea.KeyPgDown:
		return []byte{27, '[', '6', '~'}
	case tea.KeyDelete:
		return []byte{27, '[', '3', '~'}
	}
	return nil
}
